CREATE DATABASE IF NOT EXISTS master;
CREATE DATABASE IF NOT EXISTS slave1;

USE master;

CREATE TABLE IF NOT EXISTS person
(
  id   INT(11) PRIMARY KEY NOT NULL
  COMMENT '主键' AUTO_INCREMENT,
  name VARCHAR(20) COMMENT '姓名',
  age  INT(11)
);

USE slave1;

CREATE TABLE IF NOT EXISTS person
(
  id   INT(11) PRIMARY KEY NOT NULL
  COMMENT '主键' AUTO_INCREMENT,
  name VARCHAR(20) COMMENT '姓名',
  age  INT(11)
);